export const teamNames = {
  DE: "Alemanha",
  SA: "Arábia Saudita",
  AR: "Argentina",
  AU: "Austrália",
  BE: "Bélgica",
  BR: "Brasil",
  CM: "Camarões",
  CA: "Canadá",
  QA: "Catar",
  KR: "Coreia do Sul",
  CR: "Costa Rica",
  HR: "Croácia",
  DK: "Dinamarca",
  EC: "Equador",
  ES: "Espanha",
  US: "Estados Unidos",
  FR: "França",
  GH: "Gana",
  NL: "Holanda",
  "GB-ENG": "Inglaterra",
  IR: "Irã",
  JP: "Japão",
  MA: "Marrocos",
  MX: "México",
  "GB-WLS": "País de Gales",
  PL: "Polônia",
  PT: "Portugal",
  SN: "Senegal",
  RS: "Sérvia",
  CH: "Suíça",
  TN: "Tunísia",
  UY: "Uruguai",
};
